---
sidebar: sidebar 
permalink: ai-policy.html 
---
= Politique interdisant l'utilisation de contenu généré par l'IA dans la documentation technique de NetApp
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Chez NetApp, nous apprécions l'expertise de nos employés, sous-traitants et partenaires qui nous aide à créer, publier et maintenir une documentation technique précise, pertinente et utile pour nos clients. Nous pensons que l'utilisation du contenu généré par l'IA peut compromettre ces valeurs et nuire à l'intégrité et à la précision de notre documentation. NetApp a donc pour politique d'interdire la publication de contenu généré par l'IA qui n'a pas été vérifié et validé par un humain. Cela s'applique à toute la documentation technique publiée sur docs.netapp.com. Il convient de noter que cette politique est similaire à la politique NetApp qui interdit l'utilisation de modèles de langues pour écrire du code pour les produits qu'elle vend.

Tous les contributeurs NetAppDocs doivent respecter la politique suivante :

* Nous n'autorisons pas la publication de la documentation destinée aux clients (comment utiliser les produits NetApp) générée par l'IA sans examen et validation humains. Cela comprend les documents écrits, les graphiques, les contenus multimédias ou d'autres documents publiés sur docs.netapp.com. Tout le contenu publié sur docs.netapp.com doit être vérifié et validé par les créateurs de contenu humain.
* Une partie du rôle de créateur de contenu pour docs.netapp.com implique de respecter le style et les guides de contributeur. Cela implique de rester informé des derniers développements du contenu généré par l'IA et de leurs implications pour la documentation technique NetApp.
* Tous les employés, sous-traitants et partenaires doivent se conformer à la politique. Des violations répétées peuvent entraîner la suspension des privilèges de création.


Les contributeurs NetAppDocs doivent garder à l'esprit les points suivants :

* Toutes les technologies de génération de contenu basées sur l'IA intégrées dans les logiciels que vous avez installés sur votre ordinateur de travail, y compris ceux comme Microsoft 365 Co-pilot, envoient vos données à l'entreprise qui héberge la technologie d'assistance. N'invitez pas une telle technologie à utiliser du contenu confidentiel de l'entreprise, y compris, mais sans s'y limiter, les spécifications des fonctionnalités de produits non commercialisés.
* N'utilisez pas les technologies publiques d'IA pour générer ou modifier la documentation technique pour les produits **non commercialisés**, les versions de produits ou les fonctionnalités des produits.
* Les droits d'auteur relatifs à la nouvelle documentation technique doivent rester au sein de NetApp et ne doivent pas être communiqués à des tiers avant les dates officielles de publication du produit et la publication de la documentation technique correspondante.
* N'envoyez pas de documentation confidentielle, de nouveau contenu ou de tout contenu écrit après 2021, y compris des URL, dans ai (ChatGPT ou tout autre outil). Toutes les informations fournies par ChatGPT font partie de son dataset d'entraînement, qui à son tour devient la propriété d'OpenAI et peut être utilisé par eux et leurs utilisateurs. Bien que la plupart de ces données soient accessibles au public, nous ne voulons pas entraîner le modèle sur notre propre propriété intellectuelle.

